SELECT * FROM Customer;

DELETE FROM Customer WHERE cid=1003;
SHOW TABLES;

SELECT * FROM Account;



DELETE FROM Account WHERE aid=3024;
DELETE FROM Account WHERE aid=3025;
DELETE FROM Account WHERE aid=3026;
DELETE FROM Account WHERE aid=3021;
DELETE FROM Account WHERE aid=3022;

DELETE FROM Customer WHERE cid=1008;
DELETE FROM Customer WHERE cid=1009;
